name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/tubechat_backend
            git status
            git pull origin main
            /usr/local/bin/docker-compose build
            /usr/local/bin/docker-compose up -d
            /usr/local/bin/docker-compose exec -T web python manage.py migrate
